### ISSUE TITLE
latest npm release is broken

### ISSUE THREAD

**Issue by talarari** [JackDanielsAndCode/react-native-multi-slider#21]
there's a duplicate react native dependency and packager crashes.
i installed it as a git dependency and it works fine, a new release is required.

**Comment by gudmundurmar** [comment]
Also need a new release that has these changes...
https://github.com/JackDanielsAndCode/react-native-multi-slider/pull/18

**Comment by jrans** [comment]
Updated npm, sorry for the delay!
