### ISSUE TITLE
Donate the npm package name?

### ISSUE THREAD

**Issue by ptomasroos** [JackDanielsAndCode/react-native-multi-slider#58]
Hi !

As of Gradle 5.0 package's can't contain a @ symbol which my multislider has been published under for over a year and its actively maintained and as a significant amount of downloads per week.

Would you consider to donate your outdated package name to me so I can republish it under react-native-multi-slider instead of keeping it scoped which won't work in the beginning of 2019 any more?

Many thanks for considering. ptomasroos@gmail.com

https://www.npmjs.com/package/react-native-multi-slider
https://www.npmjs.com/package/@ptomasroos/react-native-multi-slider

**Comment by Northshoot** [comment]
Would be great!
